### ISSUE TITLE
Error in CubeCobraService!

### ISSUE THREAD

**Issue by cbs38139** [ynvaser/deckscraper#7]
I get this error message when running cubecobe only script:

2023-10-25 21:07:37.736 ERROR 742 --- [           main] s.b.deckscraper.input.CubeCobraService   : Error in CubeCobraService!

com.dropbox.core.v2.files.GetMetadataErrorException: Exception in 2/files/get_metadata: {".tag":"path","path":"not_found"}
	at com.dropbox.core.v2.files.DbxUserFilesRequests.getMetadata(DbxUserFilesRequests.java:1580) ~[dropbox-core-sdk-5.4.4.jar!/:na]
	at com.dropbox.core.v2.files.DbxUserFilesRequests.getMetadata(DbxUserFilesRequests.java:1603) ~[dropbox-core-sdk-5.4.4.jar!/:na]
	at systems.bdev.deckscraper.input.CubeCobraService.refreshCubeDatabase(CubeCobraService.java:52) ~[classes!/:na]
	at systems.bdev.deckscraper.service.DeckScraperService.run(DeckScraperService.java:101) ~[classes!/:na]
	at systems.bdev.deckscraper.DeckScraperApplication.main(DeckScraperApplication.java:16) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[deckscraper.jar:na]

2023-10-25 21:07:37.736 ERROR 742 --- [           main] s.b.d.service.DeckScraperService         : Something went wrong :(

java.lang.RuntimeException: com.dropbox.core.v2.files.GetMetadataErrorException: Exception in 2/files/get_metadata: {".tag":"path","path":"not_found"}
	at systems.bdev.deckscraper.input.CubeCobraService.refreshCubeDatabase(CubeCobraService.java:81) ~[classes!/:na]
	at systems.bdev.deckscraper.service.DeckScraperService.run(DeckScraperService.java:101) ~[classes!/:na]
	at systems.bdev.deckscraper.DeckScraperApplication.main(DeckScraperApplication.java:16) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[deckscraper.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[deckscraper.jar:na]
Caused by: com.dropbox.core.v2.files.GetMetadataErrorException: Exception in 2/files/get_metadata: {".tag":"path","path":"not_found"}
	at com.dropbox.core.v2.files.DbxUserFilesRequests.getMetadata(DbxUserFilesRequests.java:1580) ~[dropbox-core-sdk-5.4.4.jar!/:na]
	at com.dropbox.core.v2.files.DbxUserFilesRequests.getMetadata(DbxUserFilesRequests.java:1603) ~[dropbox-core-sdk-5.4.4.jar!/:na]
	at systems.bdev.deckscraper.input.CubeCobraService.refreshCubeDatabase(CubeCobraService.java:52) ~[classes!/:na]
	... 10 common frames omitted

**Comment by ynvaser** [comment]
This is an expected side effect of the CubeCobra API change. I haven't got around to fixing it yet.
As a workaround, if you have an old database file with the CubeCobra data, you can copy/paste that into your new installation.
